### ISSUE TITLE
Closed blocks hard to identify in dark mode

### ISSUE THREAD

**Issue by szczurek1k** [nmartin84/logseq-chocolate#2]
Hi!
The background of the closed bullet in the dark mode seems to blend it too much with the main background. 
This makes it hard for me to see if there's a closed bullet.

It the readme's screenshot, the background of the bullet is lighter and that makes it easier to identify. 

Light on 0.6.1           |  Dark on 0.6.1  | Dark on readme
:-------------------------:|:-------------------------:|:-------------------------:
<img width="345" alt="Screen Shot 2022-02-26 at 11 00 52" src="https://user-images.githubusercontent.com/87086847/155838956-3962f0c1-9a50-4d4b-8d8f-5c6638eca24b.png">|  <img width="343" alt="Screen Shot 2022-02-26 at 11 00 39" src="https://user-images.githubusercontent.com/87086847/155838951-945498ec-cf0f-404e-b11c-15a4ddc3e177.png"> | <img width="538" alt="Screen Shot 2022-02-26 at 11 01 37" src="https://user-images.githubusercontent.com/87086847/155838962-05e740cf-ab03-452f-81ae-3b017a8fa9f5.png">

**Comment by nmartin84** [comment]
Thanks for the issue. I pushed a fix for this a few minutes ago and updated the version 0.1.3..
